### ISSUE TITLE
Samsung Odyssey

### ISSUE THREAD

**Issue by mpresence** [OpenTPCast/Docs#22]
Does anyone know if OpenTPCast will work with WMR headsets like the Samsung Odyssey.

**Comment by NGenesis** [comment]
TLDR: It won't work the way you want it to.

The USB/5GHz side of the TPCast (the part that OpenTPCast deals with) will work fine with WMR headsets, however the HDMI/60GHz transmitter/receiver will not work due to the EDIDs being hardcoded into the kit for specific headsets (Vive headset EDID for the Vive TPCast, Rift headset EDID for the Rift TPCast).

**Comment by mpresence** [comment]
Thanks a lot...you just saved me a lot of money :)
