### ISSUE TITLE
Unable to connect with VirtualHere

### ISSUE THREAD

**Issue by light4speed** [OpenTPCast/Docs#6]
After following the opentpcast install guide completely and after spending sometime trying different settings, options and configurations I have been unable to get virtualhere to detect the tpcast usb hub. Virtualhere will forever remain on "connecting to usb hub..."

So I can never get to the point to activate the virtualhere licence as none of the usb devices are ever found. Note, I am using a different SD card then the stock one supplied with the TPCAST but, I confirmed that backing up the original image and flashing it on the new card still works when using the TPCAST software.

Is there some connection step that I'm missing? 
Thanks for any help!

**Comment by NGenesis** [comment]
I would recommend using the [Community Discord](https://discord.gg/kAbqRGC) to troubleshoot configuration issues.

In the meantime:
* Check the TPCast router's DHCP list while the TPCast power box is turned on to make sure that it is connecting to it, and ping the TPCast power box from your computer to make sure it can be reached.
* Ensure that you have Bonjour installed so that VirtualHere can detect the TPCast power box, otherwise you will have to manually specify the IP address of the TPCast power box in VirtualHere USB Client by right clicking `USB Hubs` > `Specify Hubs...` > `Add` > `192.168.XXX.XXX:7575` > `OK`.

**Comment by light4speed** [comment]
Thanks for the help, I got it working now! I have Bonjour installed but, I think mine might be messed up. Anyway, by doing "Specify Hubs" and adding the address (as discovered through the router) I was able to get it hooked up with no other issues. 

Got VirtualHere to start with windows and then steamvr to start when detected = perfect hassle free setup.

This is a great addon to the TPCAST (should have been part of the original package...). If you guys ever figure out how to integrate the camera correctly (if even possible) this modification would be 100% perfect. Great work!
