### ISSUE TITLE
Virtualhere Won't Show TPCast Power Box

### ISSUE THREAD

**Issue by safetychief8** [OpenTPCast/Docs#9]
Can't get power box to show in Virtualhere directly and don't know the power box's IP address. Does anyone know what  the IP address flashed for open TPCast is?

**Comment by NGenesis** [comment]
If VirtualHere USB Client is not detecting the TPCast power box:
* Check the TPCast router's DHCP list while the TPCast power box is turned on to make sure that it is connected to the network, and ping the TPCast power box from your computer to make sure it can be reached.
* Ensure that you have Bonjour installed and your firewall is not blocking Bonjour or VirtualHere USB Client so that VirtualHere can detect the TPCast power box, otherwise you will have to manually specify the IP address of the TPCast power box in VirtualHere USB Client by right clicking USB Hubs > Specify Hubs... > Add > 192.168.XXX.XXX:7575 > OK.

The power box's IP is assigned via DHCP on your TPCast router, so you can check using the router's control panel can at http://192.168.144.1 (CE) or http://192.168.1.1 (PRE) using a web browser with the following credentials:
Username: tproot (if prompted)
Password: 8427531 (CE) or 12345678 (PRE)

Also, please use the community discord at https://discord.gg/kAbqRGC to troubleshoot issues rather than posting a bug report.
